# Generated by Django 4.2.6 on 2023-10-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_caffeine_name_alter_coffeetype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
