# Generated by Django 4.2.6 on 2023-10-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_category_id_delete_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='mohammed', upload_to='product/images'),
            preserve_default=False,
        ),
    ]
