# Generated by Django 4.2.6 on 2023-10-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_id',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
